version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1.4

    working_directory: ~/repo

    steps:
      - checkout

      # Check Node & npm versions
      - run:
          name: "Checking versions"
          command: |
              node --version
              npm --version

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Install node modules
      - run:
          name: "Install dependencies"
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run tests
      - run:
          name: "Checking for type errors"
          command: npm run flow
      - run:
          name: "Running unit and snapshot tests"
          command: npm run test

      # Build project
      - run:
          name: "Building production version"
          command: npm run build
